# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  test-suite:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest tests/

  train-and-quantize:
    name: Train and Quantize
    runs-on: ubuntu-latest
    needs: test-suite

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train.py
      run: python src/train.py

    - name: Run quantize.py
      run: python src/quantize.py

  build-and-test-container:
    name: Build Docker & Run Predict
    runs-on: ubuntu-latest
    needs: train-and-quantize

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker Image
      run: docker build -t mlops-predict .

    - name: Run Docker Container
      run: docker run --rm mlops-predict